# Configure mobile/.env for how you run the API
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts/setup-env.ps1 -Mode emulator
#   powershell -ExecutionPolicy Bypass -File scripts/setup-env.ps1 -Mode phone
#   powershell -ExecutionPolicy Bypass -File scripts/setup-env.ps1 -Mode staging -ApiHost https://your-domain.com

param(
  [ValidateSet('emulator', 'phone', 'staging')]
  [string]$Mode = 'emulator',
  [string]$ApiHost = '',
  [int]$ApiPort = 5050
)

$ErrorActionPreference = "Stop"
$mobileRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$mobileRoot = Split-Path -Parent $mobileRoot
$outFile = Join-Path $mobileRoot ".env"

function Get-LanIp {
  $ip = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object { $_.InterfaceAlias -notmatch 'Loopback|vEthernet|WSL' -and $_.IPAddress -notlike '169.*' } |
    Select-Object -First 1 -ExpandProperty IPAddress
  if (-not $ip) { $ip = '192.168.1.100' }
  return $ip
}

switch ($Mode) {
  'emulator' {
    # 10.0.2.2 is the Android emulator alias for the dev PC (localhost on the device is wrong)
    $base = "http://10.0.2.2:$ApiPort"
    $note = "Android emulator (host PC via 10.0.2.2)"
  }
  'phone' {
    $lan = Get-LanIp
    $base = "http://${lan}:$ApiPort"
    $note = "Physical phone on same Wi-Fi as PC ($lan)"
  }
  'staging' {
    if (-not $ApiHost) {
      Write-Error "staging mode requires -ApiHost https://your-domain.com"
    }
    $base = $ApiHost.TrimEnd('/')
    $note = "Production/staging server"
  }
}

$apiUrl = if ($base -match '/api$') { $base } else { "$base/api" }
$socketUrl = $base -replace '/api$', ''

$content = @"
# Nurse Care mobile - $note
# Generated by scripts/setup-env.ps1 -Mode $Mode

EXPO_PUBLIC_API_URL=$apiUrl
EXPO_PUBLIC_SOCKET_URL=$socketUrl
"@

Set-Content -Path $outFile -Value $content -Encoding UTF8
Write-Host ""
Write-Host "Wrote mobile/.env ($Mode)" -ForegroundColor Green
Write-Host "  EXPO_PUBLIC_API_URL=$apiUrl"
Write-Host "  EXPO_PUBLIC_SOCKET_URL=$socketUrl"
Write-Host ""
if ($Mode -eq 'phone') {
  Write-Host "Start Metro for physical phone (LAN QR - not localhost):" -ForegroundColor Cyan
  Write-Host "  cd mobile"
  Write-Host "  npm run start:phone"
  Write-Host ""
  Write-Host "Phone and PC must be on the same Wi-Fi. Allow ports in firewall (Admin PowerShell):"
  Write-Host "  npm run open-firewall"
} elseif ($Mode -eq 'emulator') {
  Write-Host "Start Metro for Android emulator:"
  Write-Host "  cd mobile"
  Write-Host "  npm run start:emulator"
} else {
  Write-Host "Start: cd mobile; npm start"
}
Write-Host ""
