# Generates repo-root .env for local Docker Compose from backend/.env
# Usage: powershell -ExecutionPolicy Bypass -File scripts/setup-local-env.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$backendEnv = Join-Path $root "backend\.env"
$outEnv = Join-Path $root ".env"

if (-not (Test-Path $backendEnv)) {
  Write-Error "backend/.env not found. Run: cd backend && npm run db:setup"
}

$lines = Get-Content $backendEnv
$dbUrl = ($lines | Where-Object { $_ -match '^DATABASE_URL=' }) -replace '^DATABASE_URL=', ''
if (-not $dbUrl) {
  Write-Error "DATABASE_URL missing in backend/.env"
}

# Inside Docker, 127.0.0.1 is the container — point at the host Postgres instead.
$dockerDbUrl = $dbUrl -replace '@127\.0\.0\.1:', '@host.docker.internal:'
$dockerDbUrl = $dockerDbUrl -replace '@localhost:', '@host.docker.internal:'

$jwt = ($lines | Where-Object { $_ -match '^JWT_SECRET=' }) -replace '^JWT_SECRET=', ''
if (-not $jwt) { $jwt = "dev-change-me-use-long-random-string-min-32-chars" }

$content = @"
# Auto-generated by scripts/setup-local-env.ps1 - local Docker + dev
# Regenerate after changing backend/.env

DATABASE_URL=$dockerDbUrl
JWT_SECRET=$jwt
JWT_EXPIRES_IN=7d
CLIENT_ORIGIN=http://localhost:8080,http://localhost:5173

# Uncomment once to seed demo data when API container starts:
# SEED_ON_START=1
"@

Set-Content -Path $outEnv -Value $content -Encoding UTF8
Write-Host "`nCreated $outEnv" -ForegroundColor Green
Write-Host "  DATABASE_URL uses host.docker.internal (for Docker)"
Write-Host "`nNext:"
Write-Host "  1. Install Docker Desktop"
Write-Host "  2. docker compose up --build"
Write-Host "  3. Web: http://localhost:8080  API: http://localhost:5050/api/health`n"
